# Generated by Django 4.2.3 on 2024-12-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='departamento',
            new_name='funcao',
        ),
    ]
