# Generated by Django 4.2.3 on 2024-12-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_departamento_funcionario_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='isGerente',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
